name: Check CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  checks:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 8
        id: setup-java-8
        uses: actions/setup-java@v4
        with:
          java-version: '8'

      - name: Setup JDK
        id: setup-java
        uses: actions/setup-java@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=${{ steps.setup-java.outputs.path }}" >> $GITHUB_ENV

      - name: Check
        run: ./gradlew --continue check

      - name: Publish Test Results
        uses: scacap/action-surefire-report@v1
        if: always()
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
        with:
          check_name: check-ci test report
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: '**/build/test-results/test/TEST-*.xml'
